# Generated by Django 4.2.26 on 2025-11-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField(blank=True)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('docker_compose_content', models.TextField(blank=True, help_text='Docker compose YAML content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_stacks', to='services.server')),
            ],
            options={
                'ordering': ['server__name', 'name'],
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_healthy', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='services.server')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='services.server')),
            ],
            options={
                'ordering': ['source__name', 'target__name'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.CreateModel(
            name='ContainerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('ports', models.JSONField(default=list, help_text='List of exposed ports')),
                ('volumes', models.JSONField(default=list, help_text='List of volumes')),
                ('networks', models.JSONField(default=list, help_text='List of networks')),
                ('depends_on', models.JSONField(default=list, help_text='List of service dependencies')),
                ('environment', models.JSONField(default=dict, help_text='Environment variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_services', to='services.servicestack')),
            ],
            options={
                'ordering': ['stack__name', 'service_name'],
                'unique_together': {('stack', 'service_name')},
            },
        ),
    ]
